apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }}

  DYNAMO_DB_ENDPOINT: http://{{ .Release.Name }}-{{ .Values.configMap.dynamo_db }}.{{ .Release.Namespace }}:4566
